/**
 * NODEFORGE - Visual Programming Studio
 * Gelistirici: Developed By K7~
 * C++ 20 & Unreal Engine Kod Uretim Motoru
 */

import { ara_proje_temsili, ara_komut, ara_ifade } from './ara_temsil';

export function cpp_kodu_uret(ara_temsil: ara_proje_temsili): string {
  const satirlar: string[] = [];

  satirlar.push('// ==========================================');
  satirlar.push('// Generated by NODEFORGE - Visual Programming Studio');
  satirlar.push('// Developed By K7~');
  satirlar.push('// Target: ISO C++20 / Unreal Engine C++ Style');
  satirlar.push('// ==========================================');
  satirlar.push('');
  satirlar.push('#include <iostream>');
  satirlar.push('#include <string>');
  satirlar.push('#include <vector>');
  satirlar.push('#include <chrono>');
  satirlar.push('#include <thread>');
  satirlar.push('#include <random>');
  satirlar.push('');
  satirlar.push('using namespace std;');
  satirlar.push('');

  // Değişkenler
  if (ara_temsil.degisken_bildirimleri.length > 0) {
    satirlar.push('// Proje Değişkenleri');
    ara_temsil.degisken_bildirimleri.forEach(d => {
      const cpp_tip = cpp_tipine_cevir(d.tip);
      const cpp_val = cpp_degerine_cevir(d.ilk_deger, d.tip);
      satirlar.push(`${cpp_tip} ${d.ad} = ${cpp_val};`);
    });
    satirlar.push('');
  }

  // Fonksiyonlar
  if (ara_temsil.fonksiyon_bildirimleri.length > 0) {
    satirlar.push('// Özel Fonksiyonlar');
    ara_temsil.fonksiyon_bildirimleri.forEach(fn => {
      satirlar.push(`void ${fn.fonksiyon_adi}() {`);
      if (fn.fonksiyon_govdesi && fn.fonksiyon_govdesi.length > 0) {
        fn.fonksiyon_govdesi.forEach(k => {
          satirlar.push(`    ${cpp_komut_satiri(k)}`);
        });
      }
      satirlar.push('}');
      satirlar.push('');
    });
  }

  // int main()
  satirlar.push('int main() {');
  satirlar.push('    cout << "[NODEFORGE] C++ Program Başlatıldı." << endl;');
  satirlar.push('');

  if (ara_temsil.ana_akis_komutlari.length === 0) {
    satirlar.push('    // Boş akış');
  } else {
    ara_temsil.ana_akis_komutlari.forEach(komut => {
      satirlar.push(cpp_komut_yaz(komut, 1));
    });
  }

  satirlar.push('');
  satirlar.push('    cout << "[NODEFORGE] Yürütme Tamamlandı." << endl;');
  satirlar.push('    return 0;');
  satirlar.push('}');

  return satirlar.join('\n');
}

function cpp_tipine_cevir(tip: string): string {
  switch (tip) {
    case 'sayi': return 'double';
    case 'metin': return 'string';
    case 'mantiksal': return 'bool';
    case 'dizi': return 'vector<string>';
    default: return 'auto';
  }
}

function cpp_degerine_cevir(deger: any, tip: string): string {
  if (tip === 'sayi') return Number(deger || 0).toString();
  if (tip === 'mantiksal') return deger ? 'true' : 'false';
  if (tip === 'metin') return JSON.stringify(String(deger || ''));
  if (tip === 'dizi') return '{}';
  return '0';
}

function cpp_ifade_yaz(ifade?: ara_ifade): string {
  if (!ifade) return '""';
  if (ifade.tur === 'sabit') return JSON.stringify(ifade.deger);
  if (ifade.tur === 'degisken') return String(ifade.deger);
  if (ifade.tur === 'ikili_islem') {
    if (ifade.operator === '[]') {
      return `${cpp_ifade_yaz(ifade.sol)}[${cpp_ifade_yaz(ifade.sag)}]`;
    }
    if (ifade.operator === '**') {
      return `pow(${cpp_ifade_yaz(ifade.sol)}, ${cpp_ifade_yaz(ifade.sag)})`;
    }
    return `(${cpp_ifade_yaz(ifade.sol)} ${ifade.operator} ${cpp_ifade_yaz(ifade.sag)})`;
  }
  if (ifade.tur === 'mantik_islem') {
    if (ifade.operator === '!') return `!(${cpp_ifade_yaz(ifade.sol)})`;
    return `(${cpp_ifade_yaz(ifade.sol)} ${ifade.operator} ${cpp_ifade_yaz(ifade.sag)})`;
  }
  if (ifade.tur === 'dize_birlestir') {
    const ayrac = ifade.ek_bilgi?.ayrac || '';
    return `(to_string(${cpp_ifade_yaz(ifade.sol)}) + "${ayrac}" + to_string(${cpp_ifade_yaz(ifade.sag)}))`;
  }
  if (ifade.tur === 'dize_islem') {
    if (ifade.operator === 'uzunluk') return `(${cpp_ifade_yaz(ifade.sol)}.length())`;
    if (ifade.operator === 'iceriyor') return `(${cpp_ifade_yaz(ifade.sol)}.find(${cpp_ifade_yaz(ifade.sag)}) != string::npos)`;
  }
  if (ifade.tur === 'rastgele') {
    return `(rand() % (int)(${cpp_ifade_yaz(ifade.sag)} - ${cpp_ifade_yaz(ifade.sol)} + 1) + (int)${cpp_ifade_yaz(ifade.sol)})`;
  }
  if (ifade.tur === 'matematik_fonksiyon') {
    const fn = ifade.fonksiyon_adi || 'abs';
    const args = (ifade.argumanlar || []).map(a => cpp_ifade_yaz(a));
    if (fn === 'min') return `std::min(${args.join(', ')})`;
    if (fn === 'max') return `std::max(${args.join(', ')})`;
    if (fn === 'round') return `std::round(${args[0] || '0'})`;
    if (fn === 'floor') return `std::floor(${args[0] || '0'})`;
    if (fn === 'ceil') return `std::ceil(${args[0] || '0'})`;
    if (fn === 'sqrt') return `std::sqrt(${args[0] || '0'})`;
    if (fn === 'abs') return `std::abs(${args[0] || '0'})`;
    if (fn === 'pow') return `std::pow(${args[0] || '0'}, ${args[1] || '1'})`;
    return `std::${fn}(${args.join(', ')})`;
  }
  if (ifade.tur === 'fonksiyon_cagrisi') {
    const args = (ifade.argumanlar || []).map(a => cpp_ifade_yaz(a)).join(', ');
    return `${ifade.deger}(${args})`;
  }
  return '""';
}

function cpp_komut_satiri(komut: ara_komut): string {
  switch (komut.tur) {
    case 'konsol_yaz':
      return `cout << ${cpp_ifade_yaz(komut.mesaj)} << endl;`;
    case 'konsol_uyari':
      return `cerr << "[WARN] " << ${cpp_ifade_yaz(komut.mesaj)} << endl;`;
    case 'degisken_ata':
      return `${komut.degisken_adi} = ${cpp_ifade_yaz(komut.ifade)};`;
    case 'degisken_artir':
      return `${komut.degisken_adi} += ${cpp_ifade_yaz(komut.ifade)};`;
    case 'gecikme':
      return `this_thread::sleep_for(chrono::milliseconds(${komut.sure_ms || 1000}));`;
    case 'fonksiyon_cagir':
      return `${komut.fonksiyon_adi}();`;
    case 'fonksiyon_donusu':
      return `return ${cpp_ifade_yaz(komut.ifade)};`;
    default:
      return '// komut';
  }
}

function cpp_komut_yaz(komut: ara_komut, girinti_seviyesi: number): string {
  const girinti = '    '.repeat(girinti_seviyesi);

  if (komut.tur === 'kosul_blogu') {
    const satirlar: string[] = [];
    satirlar.push(`${girinti}if (${cpp_ifade_yaz(komut.kosul)}) {`);
    if (komut.dogru_govde && komut.dogru_govde.length > 0) {
      komut.dogru_govde.forEach(k => satirlar.push(cpp_komut_yaz(k, girinti_seviyesi + 1)));
    }
    satirlar.push(`${girinti}}`);
    if (komut.yanlis_govde && komut.yanlis_govde.length > 0) {
      satirlar.push(`${girinti}else {`);
      komut.yanlis_govde.forEach(k => satirlar.push(cpp_komut_yaz(k, girinti_seviyesi + 1)));
      satirlar.push(`${girinti}}`);
    }
    return satirlar.join('\n');
  }

  if (komut.tur === 'dongu_for') {
    const satirlar: string[] = [];
    const basla = cpp_ifade_yaz(komut.baslangic);
    const bitis = cpp_ifade_yaz(komut.bitis);
    satirlar.push(`${girinti}for (int i = ${basla}; i <= ${bitis}; i++) {`);
    if (komut.dongu_govdesi && komut.dongu_govdesi.length > 0) {
      komut.dongu_govdesi.forEach(k => satirlar.push(cpp_komut_yaz(k, girinti_seviyesi + 1)));
    }
    satirlar.push(`${girinti}}`);
    return satirlar.join('\n');
  }

  if (komut.tur === 'dongu_while') {
    const satirlar: string[] = [];
    satirlar.push(`${girinti}while (${cpp_ifade_yaz(komut.kosul)}) {`);
    if (komut.dongu_govdesi && komut.dongu_govdesi.length > 0) {
      komut.dongu_govdesi.forEach(k => satirlar.push(cpp_komut_yaz(k, girinti_seviyesi + 1)));
    }
    satirlar.push(`${girinti}}`);
    return satirlar.join('\n');
  }

  return `${girinti}${cpp_komut_satiri(komut)}`;
}
