/**
 * NODEFORGE - Visual Programming Studio
 * Gelistirici: Developed By K7~
 * C# & Unity Kod Uretim Motoru
 */

import { ara_proje_temsili, ara_komut, ara_ifade } from './ara_temsil';

export function csharp_kodu_uret(ara_temsil: ara_proje_temsili): string {
  const satirlar: string[] = [];

  satirlar.push('// ==========================================');
  satirlar.push('// Generated by NODEFORGE - Visual Programming Studio');
  satirlar.push('// Developed By K7~');
  satirlar.push('// Target: C# 12 / .NET 8.0 / Unity Compatible');
  satirlar.push('// ==========================================');
  satirlar.push('');
  satirlar.push('using System;');
  satirlar.push('using System.Collections.Generic;');
  satirlar.push('using System.Threading.Tasks;');
  satirlar.push('');
  satirlar.push('namespace NodeForgeApp');
  satirlar.push('{');
  satirlar.push('    public static class Program');
  satirlar.push('    {');

  // Değişkenler
  if (ara_temsil.degisken_bildirimleri.length > 0) {
    satirlar.push('        // Proje Değişkenleri');
    ara_temsil.degisken_bildirimleri.forEach(d => {
      const cs_tip = csharp_tipine_cevir(d.tip);
      const cs_val = csharp_degerine_cevir(d.ilk_deger, d.tip);
      satirlar.push(`        public static ${cs_tip} ${d.ad} = ${cs_val};`);
    });
    satirlar.push('');
  }

  // Fonksiyonlar
  if (ara_temsil.fonksiyon_bildirimleri.length > 0) {
    satirlar.push('        // Özel Fonksiyonlar');
    ara_temsil.fonksiyon_bildirimleri.forEach(fn => {
      satirlar.push(`        public static void ${fn.fonksiyon_adi}()`);
      satirlar.push('        {');
      if (fn.fonksiyon_govdesi && fn.fonksiyon_govdesi.length > 0) {
        fn.fonksiyon_govdesi.forEach(k => {
          satirlar.push(`            ${csharp_komut_satiri(k)}`);
        });
      }
      satirlar.push('        }');
      satirlar.push('');
    });
  }

  // Main Metodu
  satirlar.push('        public static async Task Main(string[] args)');
  satirlar.push('        {');
  satirlar.push('            Console.WriteLine("[NODEFORGE] C# Program Başlatıldı.");');
  satirlar.push('');

  if (ara_temsil.ana_akis_komutlari.length === 0) {
    satirlar.push('            // Boş akış');
  } else {
    ara_temsil.ana_akis_komutlari.forEach(komut => {
      satirlar.push(csharp_komut_yaz(komut, 3));
    });
  }

  satirlar.push('');
  satirlar.push('            Console.WriteLine("[NODEFORGE] Yürütme Tamamlandı.");');
  satirlar.push('        }');
  satirlar.push('    }');
  satirlar.push('}');

  return satirlar.join('\n');
}

function csharp_tipine_cevir(tip: string): string {
  switch (tip) {
    case 'sayi': return 'double';
    case 'metin': return 'string';
    case 'mantiksal': return 'bool';
    case 'dizi': return 'List<object>';
    case 'nesne': return 'Dictionary<string, object>';
    default: return 'object';
  }
}

function csharp_degerine_cevir(deger: any, tip: string): string {
  if (tip === 'sayi') return Number(deger || 0).toString();
  if (tip === 'mantiksal') return deger ? 'true' : 'false';
  if (tip === 'metin') return JSON.stringify(String(deger || ''));
  if (tip === 'dizi') return 'new List<object>()';
  return 'null';
}

function csharp_ifade_yaz(ifade?: ara_ifade): string {
  if (!ifade) return '""';
  if (ifade.tur === 'sabit') return JSON.stringify(ifade.deger);
  if (ifade.tur === 'degisken') return String(ifade.deger);
  if (ifade.tur === 'ikili_islem') {
    if (ifade.operator === '[]') {
      return `${csharp_ifade_yaz(ifade.sol)}[(int)${csharp_ifade_yaz(ifade.sag)}]`;
    }
    if (ifade.operator === '**') {
      return `Math.Pow(${csharp_ifade_yaz(ifade.sol)}, ${csharp_ifade_yaz(ifade.sag)})`;
    }
    return `(${csharp_ifade_yaz(ifade.sol)} ${ifade.operator} ${csharp_ifade_yaz(ifade.sag)})`;
  }
  if (ifade.tur === 'mantik_islem') {
    if (ifade.operator === '!') return `!(${csharp_ifade_yaz(ifade.sol)})`;
    return `(${csharp_ifade_yaz(ifade.sol)} ${ifade.operator} ${csharp_ifade_yaz(ifade.sag)})`;
  }
  if (ifade.tur === 'dize_birlestir') {
    const ayrac = ifade.ek_bilgi?.ayrac || '';
    return `($"{csharp_ifade_yaz(ifade.sol)}${ayrac}" + ${csharp_ifade_yaz(ifade.sag)})`;
  }
  if (ifade.tur === 'dize_islem') {
    if (ifade.operator === 'uzunluk') return `(${csharp_ifade_yaz(ifade.sol)}.ToString().Length)`;
    if (ifade.operator === 'iceriyor') return `(${csharp_ifade_yaz(ifade.sol)}.ToString().Contains(${csharp_ifade_yaz(ifade.sag)}.ToString()))`;
    if (ifade.operator === 'buyuk_harf') return `(${csharp_ifade_yaz(ifade.sol)}.ToString().ToUpper())`;
    if (ifade.operator === 'kucuk_harf') return `(${csharp_ifade_yaz(ifade.sol)}.ToString().ToLower())`;
  }
  if (ifade.tur === 'rastgele') {
    return `(new Random().Next((int)${csharp_ifade_yaz(ifade.sol)}, (int)${csharp_ifade_yaz(ifade.sag)}))`;
  }
  if (ifade.tur === 'matematik_fonksiyon') {
    const fn = ifade.fonksiyon_adi || 'abs';
    const args = (ifade.argumanlar || []).map(a => csharp_ifade_yaz(a));
    if (fn === 'min') return `Math.Min(${args.join(', ')})`;
    if (fn === 'max') return `Math.Max(${args.join(', ')})`;
    if (fn === 'round') return `Math.Round(${args[0] || '0'})`;
    if (fn === 'floor') return `Math.Floor(${args[0] || '0'})`;
    if (fn === 'ceil') return `Math.Ceiling(${args[0] || '0'})`;
    if (fn === 'sqrt') return `Math.Sqrt(${args[0] || '0'})`;
    if (fn === 'abs') return `Math.Abs(${args[0] || '0'})`;
    if (fn === 'pow') return `Math.Pow(${args[0] || '0'}, ${args[1] || '1'})`;
    return `Math.${fn}(${args.join(', ')})`;
  }
  if (ifade.tur === 'fonksiyon_cagrisi') {
    const args = (ifade.argumanlar || []).map(a => csharp_ifade_yaz(a)).join(', ');
    return `${ifade.deger}(${args})`;
  }
  return '""';
}

function csharp_komut_satiri(komut: ara_komut): string {
  switch (komut.tur) {
    case 'konsol_yaz':
      return `Console.WriteLine(${csharp_ifade_yaz(komut.mesaj)});`;
    case 'konsol_uyari':
      return `Console.ForegroundColor = ConsoleColor.Yellow; Console.WriteLine("[WARN] " + ${csharp_ifade_yaz(komut.mesaj)}); Console.ResetColor();`;
    case 'degisken_ata':
      return `${komut.degisken_adi} = ${csharp_ifade_yaz(komut.ifade)};`;
    case 'degisken_artir':
      return `${komut.degisken_adi} += ${csharp_ifade_yaz(komut.ifade)};`;
    case 'gecikme':
      return `await Task.Delay(${komut.sure_ms || 1000});`;
    case 'fonksiyon_cagir':
      return `${komut.fonksiyon_adi}();`;
    case 'fonksiyon_donusu':
      return `return ${csharp_ifade_yaz(komut.ifade)};`;
    default:
      return '// komut';
  }
}

function csharp_komut_yaz(komut: ara_komut, girinti_seviyesi: number): string {
  const girinti = '    '.repeat(girinti_seviyesi);

  if (komut.tur === 'kosul_blogu') {
    const satirlar: string[] = [];
    satirlar.push(`${girinti}if (${csharp_ifade_yaz(komut.kosul)})`);
    satirlar.push(`${girinti}{`);
    if (komut.dogru_govde && komut.dogru_govde.length > 0) {
      komut.dogru_govde.forEach(k => satirlar.push(csharp_komut_yaz(k, girinti_seviyesi + 1)));
    }
    satirlar.push(`${girinti}}`);
    if (komut.yanlis_govde && komut.yanlis_govde.length > 0) {
      satirlar.push(`${girinti}else`);
      satirlar.push(`${girinti}{`);
      komut.yanlis_govde.forEach(k => satirlar.push(csharp_komut_yaz(k, girinti_seviyesi + 1)));
      satirlar.push(`${girinti}}`);
    }
    return satirlar.join('\n');
  }

  if (komut.tur === 'dongu_for') {
    const satirlar: string[] = [];
    const basla = csharp_ifade_yaz(komut.baslangic);
    const bitis = csharp_ifade_yaz(komut.bitis);
    satirlar.push(`${girinti}for (int i = (int)${basla}; i <= (int)${bitis}; i++)`);
    satirlar.push(`${girinti}{`);
    if (komut.dongu_govdesi && komut.dongu_govdesi.length > 0) {
      komut.dongu_govdesi.forEach(k => satirlar.push(csharp_komut_yaz(k, girinti_seviyesi + 1)));
    }
    satirlar.push(`${girinti}}`);
    return satirlar.join('\n');
  }

  if (komut.tur === 'dongu_while') {
    const satirlar: string[] = [];
    satirlar.push(`${girinti}while (${csharp_ifade_yaz(komut.kosul)})`);
    satirlar.push(`${girinti}{`);
    if (komut.dongu_govdesi && komut.dongu_govdesi.length > 0) {
      komut.dongu_govdesi.forEach(k => satirlar.push(csharp_komut_yaz(k, girinti_seviyesi + 1)));
    }
    satirlar.push(`${girinti}}`);
    return satirlar.join('\n');
  }

  return `${girinti}${csharp_komut_satiri(komut)}`;
}
