/**
 * NODEFORGE - Visual Programming Studio
 * Gelistirici: Developed By K7~
 * Golang Kod Uretim Motoru (Go 1.22+)
 */

import { ara_proje_temsili, ara_komut, ara_ifade } from './ara_temsil';

export function go_kodu_uret(ara_temsil: ara_proje_temsili): string {
  const satirlar: string[] = [];

  satirlar.push('// ==========================================');
  satirlar.push('// Generated by NODEFORGE - Visual Programming Studio');
  satirlar.push(`// Project: ${ara_temsil.proje_adi}`);
  satirlar.push('// Developed By K7~');
  satirlar.push('// Target: Golang 1.22+');
  satirlar.push('// ==========================================');
  satirlar.push('');
  satirlar.push('package main');
  satirlar.push('');
  satirlar.push('import (');
  satirlar.push('\t"fmt"');
  satirlar.push('\t"time"');
  satirlar.push('\t"math"');
  satirlar.push('\t"math/rand"');
  satirlar.push('\t"strings"');
  satirlar.push(')');
  satirlar.push('');

  // Global Değişkenler
  if (ara_temsil.degisken_bildirimleri.length > 0) {
    satirlar.push('var (');
    ara_temsil.degisken_bildirimleri.forEach(d => {
      const go_tip = go_tipine_cevir(d.tip);
      const go_val = go_degerine_cevir(d.ilk_deger, d.tip);
      satirlar.push(`\t${d.ad} ${go_tip} = ${go_val}`);
    });
    satirlar.push(')');
    satirlar.push('');
  }

  // Fonksiyonlar
  if (ara_temsil.fonksiyon_bildirimleri.length > 0) {
    ara_temsil.fonksiyon_bildirimleri.forEach(fn => {
      satirlar.push(`func ${fn.fonksiyon_adi}() {`);
      if (fn.fonksiyon_govdesi && fn.fonksiyon_govdesi.length > 0) {
        fn.fonksiyon_govdesi.forEach(k => {
          satirlar.push(go_komut_yaz(k, 1));
        });
      }
      satirlar.push('}');
      satirlar.push('');
    });
  }

  // func main()
  satirlar.push('func main() {');
  satirlar.push('\tfmt.Println("[NODEFORGE] Go Program Başlatıldı.")');
  satirlar.push('');

  if (ara_temsil.ana_akis_komutlari.length === 0) {
    satirlar.push('\t// Boş akış');
  } else {
    ara_temsil.ana_akis_komutlari.forEach(komut => {
      satirlar.push(go_komut_yaz(komut, 1));
    });
  }

  satirlar.push('');
  satirlar.push('\tfmt.Println("[NODEFORGE] Yürütme Tamamlandı.")');
  satirlar.push('}');

  return satirlar.join('\n');
}

function go_tipine_cevir(tip: string): string {
  switch (tip) {
    case 'sayi': return 'float64';
    case 'metin': return 'string';
    case 'mantiksal': return 'bool';
    case 'dizi': return '[]interface{}';
    default: return 'interface{}';
  }
}

function go_degerine_cevir(deger: any, tip: string): string {
  if (tip === 'sayi') return Number(deger || 0).toFixed(1);
  if (tip === 'mantiksal') return deger ? 'true' : 'false';
  if (tip === 'metin') return JSON.stringify(String(deger || ''));
  if (tip === 'dizi') return '[]interface{}{}';
  return 'nil';
}

function go_ifade_yaz(ifade?: ara_ifade): string {
  if (!ifade) return '""';
  if (ifade.tur === 'sabit') return JSON.stringify(ifade.deger);
  if (ifade.tur === 'degisken') return String(ifade.deger);
  if (ifade.tur === 'ikili_islem') {
    if (ifade.operator === '[]') {
      return `${go_ifade_yaz(ifade.sol)}[int(${go_ifade_yaz(ifade.sag)})]`;
    }
    if (ifade.operator === '**') {
      return `math.Pow(${go_ifade_yaz(ifade.sol)}, ${go_ifade_yaz(ifade.sag)})`;
    }
    return `(${go_ifade_yaz(ifade.sol)} ${ifade.operator} ${go_ifade_yaz(ifade.sag)})`;
  }
  if (ifade.tur === 'mantik_islem') {
    if (ifade.operator === '!') return `!(${go_ifade_yaz(ifade.sol)})`;
    return `(${go_ifade_yaz(ifade.sol)} ${ifade.operator} ${go_ifade_yaz(ifade.sag)})`;
  }
  if (ifade.tur === 'dize_birlestir') {
    const ayrac = ifade.ek_bilgi?.ayrac || '';
    return `fmt.Sprintf("%v${ayrac}%v", ${go_ifade_yaz(ifade.sol)}, ${go_ifade_yaz(ifade.sag)})`;
  }
  if (ifade.tur === 'dize_islem') {
    if (ifade.operator === 'uzunluk') return `float64(len(${go_ifade_yaz(ifade.sol)}))`;
    if (ifade.operator === 'iceriyor') return `strings.Contains(${go_ifade_yaz(ifade.sol)}, ${go_ifade_yaz(ifade.sag)})`;
    if (ifade.operator === 'buyuk_harf') return `strings.ToUpper(${go_ifade_yaz(ifade.sol)})`;
    if (ifade.operator === 'kucuk_harf') return `strings.ToLower(${go_ifade_yaz(ifade.sol)})`;
  }
  if (ifade.tur === 'rastgele') {
    return `(rand.Float64() * (${go_ifade_yaz(ifade.sag)} - ${go_ifade_yaz(ifade.sol)}) + ${go_ifade_yaz(ifade.sol)})`;
  }
  if (ifade.tur === 'matematik_fonksiyon') {
    const fn = ifade.fonksiyon_adi || 'abs';
    const args = (ifade.argumanlar || []).map(a => go_ifade_yaz(a));
    if (fn === 'min') return `math.Min(${args.join(', ')})`;
    if (fn === 'max') return `math.Max(${args.join(', ')})`;
    if (fn === 'round') return `math.Round(${args[0] || '0'})`;
    if (fn === 'floor') return `math.Floor(${args[0] || '0'})`;
    if (fn === 'ceil') return `math.Ceil(${args[0] || '0'})`;
    if (fn === 'sqrt') return `math.Sqrt(${args[0] || '0'})`;
    if (fn === 'abs') return `math.Abs(${args[0] || '0'})`;
    if (fn === 'pow') return `math.Pow(${args[0] || '0'}, ${args[1] || '1'})`;
    return `math.${fn}(${args.join(', ')})`;
  }
  if (ifade.tur === 'fonksiyon_cagrisi') {
    const args = (ifade.argumanlar || []).map(a => go_ifade_yaz(a)).join(', ');
    return `${ifade.deger}(${args})`;
  }
  return '""';
}

function go_komut_satiri(komut: ara_komut): string {
  switch (komut.tur) {
    case 'konsol_yaz':
      return `fmt.Println(${go_ifade_yaz(komut.mesaj)})`;
    case 'konsol_uyari':
      return `fmt.Println("[WARN]", ${go_ifade_yaz(komut.mesaj)})`;
    case 'degisken_ata':
      return `${komut.degisken_adi} = ${go_ifade_yaz(komut.ifade)}`;
    case 'degisken_artir':
      return `${komut.degisken_adi} += ${go_ifade_yaz(komut.ifade)}`;
    case 'gecikme':
      return `time.Sleep(time.Duration(${komut.sure_ms || 1000}) * time.Millisecond)`;
    case 'fonksiyon_cagir':
      return `${komut.fonksiyon_adi}()`;
    case 'fonksiyon_donusu':
      return `return ${go_ifade_yaz(komut.ifade)}`;
    default:
      return '// komut';
  }
}

function go_komut_yaz(komut: ara_komut, girinti_seviyesi: number): string {
  const girinti = '\t'.repeat(girinti_seviyesi);

  if (komut.tur === 'kosul_blogu') {
    const satirlar: string[] = [];
    satirlar.push(`${girinti}if ${go_ifade_yaz(komut.kosul)} {`);
    if (komut.dogru_govde && komut.dogru_govde.length > 0) {
      komut.dogru_govde.forEach(k => satirlar.push(go_komut_yaz(k, girinti_seviyesi + 1)));
    }
    satirlar.push(`${girinti}}`);
    if (komut.yanlis_govde && komut.yanlis_govde.length > 0) {
      satirlar.push(`${girinti}else {`);
      komut.yanlis_govde.forEach(k => satirlar.push(go_komut_yaz(k, girinti_seviyesi + 1)));
      satirlar.push(`${girinti}}`);
    }
    return satirlar.join('\n');
  }

  if (komut.tur === 'dongu_for') {
    const satirlar: string[] = [];
    const basla = go_ifade_yaz(komut.baslangic);
    const bitis = go_ifade_yaz(komut.bitis);
    const sayac = komut.sayac_adi || 'i';
    satirlar.push(`${girinti}for ${sayac} := int(${basla}); ${sayac} <= int(${bitis}); ${sayac}++ {`);
    if (komut.dongu_govdesi && komut.dongu_govdesi.length > 0) {
      komut.dongu_govdesi.forEach(k => satirlar.push(go_komut_yaz(k, girinti_seviyesi + 1)));
    }
    satirlar.push(`${girinti}}`);
    return satirlar.join('\n');
  }

  if (komut.tur === 'dongu_while') {
    const satirlar: string[] = [];
    satirlar.push(`${girinti}for ${go_ifade_yaz(komut.kosul)} {`);
    if (komut.dongu_govdesi && komut.dongu_govdesi.length > 0) {
      komut.dongu_govdesi.forEach(k => satirlar.push(go_komut_yaz(k, girinti_seviyesi + 1)));
    }
    satirlar.push(`${girinti}}`);
    return satirlar.join('\n');
  }

  return `${girinti}${go_komut_satiri(komut)}`;
}
