/**
 * NODEFORGE - Visual Programming Studio
 * Gelistirici: Developed By K7~
 * Rust Kod Uretim Motoru (Rust 2024 Edition)
 */

import { ara_proje_temsili, ara_komut, ara_ifade } from './ara_temsil';

export function rust_kodu_uret(ara_temsil: ara_proje_temsili): string {
  const satirlar: string[] = [];

  satirlar.push('// ==========================================');
  satirlar.push('// Generated by NODEFORGE - Visual Programming Studio');
  satirlar.push(`// Project: ${ara_temsil.proje_adi}`);
  satirlar.push('// Developed By K7~');
  satirlar.push('// Target: Rust 2024 Edition (Memory Safe)');
  satirlar.push('// ==========================================');
  satirlar.push('');
  satirlar.push('#![allow(unused_variables, dead_code, unused_mut)]');
  satirlar.push('use std::thread;');
  satirlar.push('use std::time::Duration;');
  satirlar.push('');

  // Fonksiyonlar
  if (ara_temsil.fonksiyon_bildirimleri.length > 0) {
    ara_temsil.fonksiyon_bildirimleri.forEach(fn => {
      satirlar.push(`fn ${fn.fonksiyon_adi}() {`);
      if (fn.fonksiyon_govdesi && fn.fonksiyon_govdesi.length > 0) {
        fn.fonksiyon_govdesi.forEach(k => {
          satirlar.push(rust_komut_yaz(k, 1));
        });
      }
      satirlar.push('}');
      satirlar.push('');
    });
  }

  // fn main()
  satirlar.push('fn main() {');
  satirlar.push('    println!("[NODEFORGE] Rust Program Başlatıldı.");');
  satirlar.push('');

  // Değişkenler main içinde mut olarak tanımlanır
  if (ara_temsil.degisken_bildirimleri.length > 0) {
    satirlar.push('    // Proje Değişkenleri');
    ara_temsil.degisken_bildirimleri.forEach(d => {
      const rs_tip = rust_tipine_cevir(d.tip);
      const rs_val = rust_degerine_cevir(d.ilk_deger, d.tip);
      satirlar.push(`    let mut ${d.ad}: ${rs_tip} = ${rs_val};`);
    });
    satirlar.push('');
  }

  if (ara_temsil.ana_akis_komutlari.length === 0) {
    satirlar.push('    // Boş akış');
  } else {
    ara_temsil.ana_akis_komutlari.forEach(komut => {
      satirlar.push(rust_komut_yaz(komut, 1));
    });
  }

  satirlar.push('');
  satirlar.push('    println!("[NODEFORGE] Yürütme Tamamlandı.");');
  satirlar.push('}');

  return satirlar.join('\n');
}

function rust_tipine_cevir(tip: string): string {
  switch (tip) {
    case 'sayi': return 'f64';
    case 'metin': return 'String';
    case 'mantiksal': return 'bool';
    case 'dizi': return 'Vec<String>';
    default: return 'String';
  }
}

function rust_degerine_cevir(deger: any, tip: string): string {
  if (tip === 'sayi') return Number(deger || 0).toFixed(1);
  if (tip === 'mantiksal') return deger ? 'true' : 'false';
  if (tip === 'metin') return `String::from(${JSON.stringify(String(deger || ''))})`;
  if (tip === 'dizi') return 'Vec::new()';
  return 'String::new()';
}

function rust_ifade_yaz(ifade?: ara_ifade): string {
  if (!ifade) return '""';
  if (ifade.tur === 'sabit') {
    if (typeof ifade.deger === 'string') return JSON.stringify(ifade.deger);
    if (typeof ifade.deger === 'number') return Number(ifade.deger).toFixed(1);
    if (typeof ifade.deger === 'boolean') return ifade.deger ? 'true' : 'false';
    return JSON.stringify(ifade.deger);
  }
  if (ifade.tur === 'degisken') return String(ifade.deger);
  if (ifade.tur === 'ikili_islem') {
    if (ifade.operator === '[]') {
      return `${rust_ifade_yaz(ifade.sol)}[${rust_ifade_yaz(ifade.sag)} as usize]`;
    }
    if (ifade.operator === '**') {
      return `(${rust_ifade_yaz(ifade.sol)} as f64).powf(${rust_ifade_yaz(ifade.sag)} as f64)`;
    }
    return `(${rust_ifade_yaz(ifade.sol)} ${ifade.operator} ${rust_ifade_yaz(ifade.sag)})`;
  }
  if (ifade.tur === 'mantik_islem') {
    if (ifade.operator === '!') return `!(${rust_ifade_yaz(ifade.sol)})`;
    return `(${rust_ifade_yaz(ifade.sol)} ${ifade.operator} ${rust_ifade_yaz(ifade.sag)})`;
  }
  if (ifade.tur === 'dize_birlestir') {
    const ayrac = ifade.ek_bilgi?.ayrac || '';
    return `format!("{}{}{}", ${rust_ifade_yaz(ifade.sol)}, "${ayrac}", ${rust_ifade_yaz(ifade.sag)})`;
  }
  if (ifade.tur === 'dize_islem') {
    if (ifade.operator === 'uzunluk') return `(${rust_ifade_yaz(ifade.sol)}.len() as f64)`;
    if (ifade.operator === 'iceriyor') return `(${rust_ifade_yaz(ifade.sol)}.contains(&${rust_ifade_yaz(ifade.sag)}))`;
    if (ifade.operator === 'buyuk_harf') return `(${rust_ifade_yaz(ifade.sol)}.to_uppercase())`;
    if (ifade.operator === 'kucuk_harf') return `(${rust_ifade_yaz(ifade.sol)}.to_lowercase())`;
  }
  if (ifade.tur === 'matematik_fonksiyon') {
    const fn = ifade.fonksiyon_adi || 'abs';
    const args = (ifade.argumanlar || []).map(a => rust_ifade_yaz(a));
    if (fn === 'min') return `f64::min(${args[0] || '0.0'} as f64, ${args[1] || '0.0'} as f64)`;
    if (fn === 'max') return `f64::max(${args[0] || '0.0'} as f64, ${args[1] || '0.0'} as f64)`;
    if (fn === 'round') return `(${args[0] || '0.0'} as f64).round()`;
    if (fn === 'floor') return `(${args[0] || '0.0'} as f64).floor()`;
    if (fn === 'ceil') return `(${args[0] || '0.0'} as f64).ceil()`;
    if (fn === 'sqrt') return `(${args[0] || '0.0'} as f64).sqrt()`;
    if (fn === 'abs') return `(${args[0] || '0.0'} as f64).abs()`;
    if (fn === 'pow') return `(${args[0] || '0.0'} as f64).powf(${args[1] || '1.0'} as f64)`;
  }
  if (ifade.tur === 'fonksiyon_cagrisi') {
    const args = (ifade.argumanlar || []).map(a => rust_ifade_yaz(a)).join(', ');
    return `${ifade.deger}(${args})`;
  }
  return '""';
}

function rust_komut_satiri(komut: ara_komut): string {
  switch (komut.tur) {
    case 'konsol_yaz':
      return `println!("{}", ${rust_ifade_yaz(komut.mesaj)});`;
    case 'konsol_uyari':
      return `eprintln!("[WARN] {}", ${rust_ifade_yaz(komut.mesaj)});`;
    case 'degisken_ata':
      return `${komut.degisken_adi} = ${rust_ifade_yaz(komut.ifade)};`;
    case 'degisken_artir':
      return `${komut.degisken_adi} += ${rust_ifade_yaz(komut.ifade)};`;
    case 'gecikme':
      return `thread::sleep(Duration::from_millis(${komut.sure_ms || 1000}));`;
    case 'fonksiyon_cagir':
      return `${komut.fonksiyon_adi}();`;
    case 'fonksiyon_donusu':
      return `return ${rust_ifade_yaz(komut.ifade)};`;
    default:
      return '// komut';
  }
}

function rust_komut_yaz(komut: ara_komut, girinti_seviyesi: number): string {
  const girinti = '    '.repeat(girinti_seviyesi);

  if (komut.tur === 'kosul_blogu') {
    const satirlar: string[] = [];
    satirlar.push(`${girinti}if ${rust_ifade_yaz(komut.kosul)} {`);
    if (komut.dogru_govde && komut.dogru_govde.length > 0) {
      komut.dogru_govde.forEach(k => satirlar.push(rust_komut_yaz(k, girinti_seviyesi + 1)));
    }
    satirlar.push(`${girinti}}`);
    if (komut.yanlis_govde && komut.yanlis_govde.length > 0) {
      satirlar.push(`${girinti}else {`);
      komut.yanlis_govde.forEach(k => satirlar.push(rust_komut_yaz(k, girinti_seviyesi + 1)));
      satirlar.push(`${girinti}}`);
    }
    return satirlar.join('\n');
  }

  if (komut.tur === 'dongu_for') {
    const satirlar: string[] = [];
    const basla = rust_ifade_yaz(komut.baslangic);
    const bitis = rust_ifade_yaz(komut.bitis);
    const sayac = komut.sayac_adi || 'i';
    satirlar.push(`${girinti}for ${sayac} in (${basla} as i64)..=(${bitis} as i64) {`);
    if (komut.dongu_govdesi && komut.dongu_govdesi.length > 0) {
      komut.dongu_govdesi.forEach(k => satirlar.push(rust_komut_yaz(k, girinti_seviyesi + 1)));
    }
    satirlar.push(`${girinti}}`);
    return satirlar.join('\n');
  }

  if (komut.tur === 'dongu_while') {
    const satirlar: string[] = [];
    satirlar.push(`${girinti}while ${rust_ifade_yaz(komut.kosul)} {`);
    if (komut.dongu_govdesi && komut.dongu_govdesi.length > 0) {
      komut.dongu_govdesi.forEach(k => satirlar.push(rust_komut_yaz(k, girinti_seviyesi + 1)));
    }
    satirlar.push(`${girinti}}`);
    return satirlar.join('\n');
  }

  return `${girinti}${rust_komut_satiri(komut)}`;
}
